//! Low-level RDMA sys crate — FFI bindings for libibverbs + librdmacm.
//!
//! Generated by `bnd-rdma-gen` — do not edit `src/rdma/` manually.

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod rdma;
pub use rdma::*;

extern crate bnd_macros as windows_link;
