//! Low-level RDMA sys crate — FFI bindings for libibverbs + librdmacm.
//!
//! Generated by `bnd-rdma-gen` — do not edit `src/rdma/` manually.

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod rdma;
pub use rdma::*;

#[cfg(feature = "ibverbs")]
pub mod ibverbs {
    pub use crate::rdma::ib_user_ioctl_verbs::*;
    pub use crate::rdma::ib_user_verbs::*;
    pub use crate::rdma::int_ll64::*;
    pub use crate::rdma::verbs::*;
    pub use crate::rdma::verbs_api::*;
}

#[cfg(feature = "rdmacm")]
pub mod rdmacm {
    pub use crate::rdma::rdma_cma::*;
    pub use crate::rdma::sa::*;
}

extern crate bnd_macros as windows_link;
