[package]
name = "rdma-io-sys"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Low-level RDMA sys crate — FFI bindings for libibverbs + librdmacm"
readme = "README.md"

[dependencies]
bnd-linux = { workspace = true, features = ["in", "pthreadtypes", "socket", "struct_timespec", "types", "unistd"] }
bnd-macros = { workspace = true }

[build-dependencies]
cc.workspace = true

[features]
default = ["ibverbs", "rdmacm", "wrapper"]
Foundation = []
# generated features
ibverbs = []
rdmacm = ["ibverbs"]
wrapper = ["ibverbs"]
