[package]
name = "rdma-io-sys"
version = "0.0.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
description = "Low-level RDMA sys crate — FFI bindings for libibverbs + librdmacm"
readme = "README.md"

[dependencies]
bnd-linux = { workspace = true, features = ["in_", "pthreadtypes", "socket", "struct_timespec", "types", "unistd"] }
bnd-macros = { workspace = true }

[build-dependencies]
cc.workspace = true

[features]
default = ["ibverbs", "rdmacm", "wrapper"]
Foundation = []
ibverbs = ["verbs", "verbs_api"]
rdmacm = ["ibverbs", "rdma_cma"]
# generated features
ib_user_ioctl_verbs = ["ib_user_verbs", "int_ll64"]
ib_user_verbs = ["int_ll64"]
int_ll64 = []
rdma_cma = ["sa", "verbs"]
sa = ["verbs"]
verbs = ["ib_user_ioctl_verbs"]
verbs_api = []
wrapper = ["ib_user_ioctl_verbs", "verbs"]
