// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap____ibv_query_port(context : *mut super::ibverbs:: ibv_context, port_num : u8, port_attr : *mut super::ibverbs:: ibv_port_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap___ibv_reg_mr(pd : *mut super::ibverbs:: ibv_pd, addr : *mut core::ffi::c_void, length : u64, access : u32, is_access_const : i32) -> *mut super::ibverbs:: ibv_mr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap___ibv_reg_mr_iova(pd : *mut super::ibverbs:: ibv_pd, addr : *mut core::ffi::c_void, length : u64, iova : u64, access : u32, is_access_const : i32) -> *mut super::ibverbs:: ibv_mr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_advise_mr(pd : *mut super::ibverbs:: ibv_pd, advice : super::ibverbs:: ib_uverbs_advise_mr_advice, flags : u32, sg_list : *mut super::ibverbs:: ibv_sge, num_sge : u32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_alloc_dm(context : *mut super::ibverbs:: ibv_context, attr : *mut super::ibverbs:: ibv_alloc_dm_attr) -> *mut super::ibverbs:: ibv_dm);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_alloc_mw(pd : *mut super::ibverbs:: ibv_pd, r#type : super::ibverbs:: ibv_mw_type) -> *mut super::ibverbs:: ibv_mw);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_alloc_null_mr(pd : *mut super::ibverbs:: ibv_pd) -> *mut super::ibverbs:: ibv_mr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_alloc_parent_domain(context : *mut super::ibverbs:: ibv_context, attr : *mut super::ibverbs:: ibv_parent_domain_init_attr) -> *mut super::ibverbs:: ibv_pd);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_alloc_td(context : *mut super::ibverbs:: ibv_context, init_attr : *mut super::ibverbs:: ibv_td_init_attr) -> *mut super::ibverbs:: ibv_td);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_attach_counters_point_flow(counters : *mut super::ibverbs:: ibv_counters, attr : *mut super::ibverbs:: ibv_counter_attach_attr, flow : *mut super::ibverbs:: ibv_flow) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_bind_mw(qp : *mut super::ibverbs:: ibv_qp, mw : *mut super::ibverbs:: ibv_mw, mw_bind : *mut super::ibverbs:: ibv_mw_bind) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_close_xrcd(xrcd : *mut super::ibverbs:: ibv_xrcd) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_cq_ex_to_cq(cq : *mut super::ibverbs:: ibv_cq_ex) -> *mut super::ibverbs:: ibv_cq);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_counters(context : *mut super::ibverbs:: ibv_context, init_attr : *mut super::ibverbs:: ibv_counters_init_attr) -> *mut super::ibverbs:: ibv_counters);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_cq_ex(context : *mut super::ibverbs:: ibv_context, cq_attr : *mut super::ibverbs:: ibv_cq_init_attr_ex) -> *mut super::ibverbs:: ibv_cq_ex);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_flow(qp : *mut super::ibverbs:: ibv_qp, flow : *mut super::ibverbs:: ibv_flow_attr) -> *mut super::ibverbs:: ibv_flow);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_flow_action_esp(ctx : *mut super::ibverbs:: ibv_context, esp : *mut super::ibverbs:: ibv_flow_action_esp_attr) -> *mut super::ibverbs:: ibv_flow_action);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_qp_ex(context : *mut super::ibverbs:: ibv_context, qp_init_attr_ex : *mut super::ibverbs:: ibv_qp_init_attr_ex) -> *mut super::ibverbs:: ibv_qp);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_rwq_ind_table(context : *mut super::ibverbs:: ibv_context, init_attr : *mut super::ibverbs:: ibv_rwq_ind_table_init_attr) -> *mut super::ibverbs:: ibv_rwq_ind_table);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_srq_ex(context : *mut super::ibverbs:: ibv_context, srq_init_attr_ex : *mut super::ibverbs:: ibv_srq_init_attr_ex) -> *mut super::ibverbs:: ibv_srq);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_create_wq(context : *mut super::ibverbs:: ibv_context, wq_init_attr : *mut super::ibverbs:: ibv_wq_init_attr) -> *mut super::ibverbs:: ibv_wq);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_dealloc_mw(mw : *mut super::ibverbs:: ibv_mw) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_dealloc_td(td : *mut super::ibverbs:: ibv_td) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_destroy_counters(counters : *mut super::ibverbs:: ibv_counters) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_destroy_flow(flow_id : *mut super::ibverbs:: ibv_flow) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_destroy_flow_action(action : *mut super::ibverbs:: ibv_flow_action) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_destroy_rwq_ind_table(rwq_ind_table : *mut super::ibverbs:: ibv_rwq_ind_table) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_destroy_wq(wq : *mut super::ibverbs:: ibv_wq) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_end_poll(cq : *mut super::ibverbs:: ibv_cq_ex));
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_flow_label_to_udp_sport(fl : u32) -> u16);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_free_dm(dm : *mut super::ibverbs:: ibv_dm) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_get_srq_num(srq : *mut super::ibverbs:: ibv_srq, srq_num : *mut u32) -> i32);
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_inc_rkey(rkey : u32) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_is_qpt_supported(caps : u32, qpt : super::ibverbs:: ibv_qp_type) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_memcpy_from_dm(host_addr : *mut core::ffi::c_void, dm : *mut super::ibverbs:: ibv_dm, dm_offset : u64, length : u64) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_memcpy_to_dm(dm : *mut super::ibverbs:: ibv_dm, dm_offset : u64, host_addr : *const core::ffi::c_void, length : u64) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_modify_cq(cq : *mut super::ibverbs:: ibv_cq, attr : *mut super::ibverbs:: ibv_modify_cq_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_modify_flow_action_esp(action : *mut super::ibverbs:: ibv_flow_action, esp : *mut super::ibverbs:: ibv_flow_action_esp_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_modify_qp_rate_limit(qp : *mut super::ibverbs:: ibv_qp, attr : *mut super::ibverbs:: ibv_qp_rate_limit_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_modify_wq(wq : *mut super::ibverbs:: ibv_wq, wq_attr : *mut super::ibverbs:: ibv_wq_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_next_poll(cq : *mut super::ibverbs:: ibv_cq_ex) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_open_qp(context : *mut super::ibverbs:: ibv_context, qp_open_attr : *mut super::ibverbs:: ibv_qp_open_attr) -> *mut super::ibverbs:: ibv_qp);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_open_xrcd(context : *mut super::ibverbs:: ibv_context, xrcd_init_attr : *mut super::ibverbs:: ibv_xrcd_init_attr) -> *mut super::ibverbs:: ibv_xrcd);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_poll_cq(cq : *mut super::ibverbs:: ibv_cq, num_entries : i32, wc : *mut super::ibverbs:: ibv_wc) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_post_recv(qp : *mut super::ibverbs:: ibv_qp, wr : *mut super::ibverbs:: ibv_recv_wr, bad_wr : *mut *mut super::ibverbs:: ibv_recv_wr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_post_send(qp : *mut super::ibverbs:: ibv_qp, wr : *mut super::ibverbs:: ibv_send_wr, bad_wr : *mut *mut super::ibverbs:: ibv_send_wr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_post_srq_ops(srq : *mut super::ibverbs:: ibv_srq, op : *mut super::ibverbs:: ibv_ops_wr, bad_op : *mut *mut super::ibverbs:: ibv_ops_wr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_post_srq_recv(srq : *mut super::ibverbs:: ibv_srq, recv_wr : *mut super::ibverbs:: ibv_recv_wr, bad_recv_wr : *mut *mut super::ibverbs:: ibv_recv_wr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_post_wq_recv(wq : *mut super::ibverbs:: ibv_wq, recv_wr : *mut super::ibverbs:: ibv_recv_wr, bad_recv_wr : *mut *mut super::ibverbs:: ibv_recv_wr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_query_device_ex(context : *mut super::ibverbs:: ibv_context, input : *const super::ibverbs:: ibv_query_device_ex_input, attr : *mut super::ibverbs:: ibv_device_attr_ex) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_query_gid_ex(context : *mut super::ibverbs:: ibv_context, port_num : u32, gid_index : u32, entry : *mut super::ibverbs:: ibv_gid_entry, flags : u32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_query_gid_table(context : *mut super::ibverbs:: ibv_context, entries : *mut super::ibverbs:: ibv_gid_entry, max_entries : u64, flags : u32) -> bnd_posix::posix::types:: ssize_t);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_query_rt_values_ex(context : *mut super::ibverbs:: ibv_context, values : *mut super::ibverbs:: ibv_values_ex) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_read_counters(counters : *mut super::ibverbs:: ibv_counters, counters_value : *mut u64, ncounters : u32, flags : u32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_reg_dm_mr(pd : *mut super::ibverbs:: ibv_pd, dm : *mut super::ibverbs:: ibv_dm, dm_offset : u64, length : u64, access : u32) -> *mut super::ibverbs:: ibv_mr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_req_notify_cq(cq : *mut super::ibverbs:: ibv_cq, solicited_only : i32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_start_poll(cq : *mut super::ibverbs:: ibv_cq_ex, attr : *mut super::ibverbs:: ibv_poll_cq_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_byte_len(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_completion_ts(cq : *mut super::ibverbs:: ibv_cq_ex) -> u64);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_completion_wallclock_ns(cq : *mut super::ibverbs:: ibv_cq_ex) -> u64);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_cvlan(cq : *mut super::ibverbs:: ibv_cq_ex) -> u16);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_dlid_path_bits(cq : *mut super::ibverbs:: ibv_cq_ex) -> u8);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_flow_tag(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_imm_data(cq : *mut super::ibverbs:: ibv_cq_ex) -> bnd_linux::linux::types:: __be32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_invalidated_rkey(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_opcode(cq : *mut super::ibverbs:: ibv_cq_ex) -> super::ibverbs:: ibv_wc_opcode);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_qp_num(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_sl(cq : *mut super::ibverbs:: ibv_cq_ex) -> u8);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_slid(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_src_qp(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_tm_info(cq : *mut super::ibverbs:: ibv_cq_ex, tm_info : *mut super::ibverbs:: ibv_wc_tm_info));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_vendor_err(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wc_read_wc_flags(cq : *mut super::ibverbs:: ibv_cq_ex) -> u32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_abort(qp : *mut super::ibverbs:: ibv_qp_ex));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_atomic_cmp_swp(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64, compare : u64, swap : u64));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_atomic_fetch_add(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64, add : u64));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_atomic_write(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64, atomic_wr : *const core::ffi::c_void));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_bind_mw(qp : *mut super::ibverbs:: ibv_qp_ex, mw : *mut super::ibverbs:: ibv_mw, rkey : u32, bind_info : *const super::ibverbs:: ibv_mw_bind_info));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_complete(qp : *mut super::ibverbs:: ibv_qp_ex) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_flush(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64, len : u64, r#type : u8, level : u8));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_local_inv(qp : *mut super::ibverbs:: ibv_qp_ex, invalidate_rkey : u32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_rdma_read(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_rdma_write(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_rdma_write_imm(qp : *mut super::ibverbs:: ibv_qp_ex, rkey : u32, remote_addr : u64, imm_data : bnd_linux::linux::types:: __be32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_send(qp : *mut super::ibverbs:: ibv_qp_ex));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_send_imm(qp : *mut super::ibverbs:: ibv_qp_ex, imm_data : bnd_linux::linux::types:: __be32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_send_inv(qp : *mut super::ibverbs:: ibv_qp_ex, invalidate_rkey : u32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_send_tso(qp : *mut super::ibverbs:: ibv_qp_ex, hdr : *mut core::ffi::c_void, hdr_sz : u16, mss : u16));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_inline_data(qp : *mut super::ibverbs:: ibv_qp_ex, addr : *mut core::ffi::c_void, length : u64));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_inline_data_list(qp : *mut super::ibverbs:: ibv_qp_ex, num_buf : u64, buf_list : *const super::ibverbs:: ibv_data_buf));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_sge(qp : *mut super::ibverbs:: ibv_qp_ex, lkey : u32, addr : u64, length : u32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_sge_list(qp : *mut super::ibverbs:: ibv_qp_ex, num_sge : u64, sg_list : *const super::ibverbs:: ibv_sge));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_ud_addr(qp : *mut super::ibverbs:: ibv_qp_ex, ah : *mut super::ibverbs:: ibv_ah, remote_qpn : u32, remote_qkey : u32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_set_xrc_srqn(qp : *mut super::ibverbs:: ibv_qp_ex, remote_srqn : u32));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_ibv_wr_start(qp : *mut super::ibverbs:: ibv_qp_ex));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdma_wrapper" "C" fn rdma_wrap_verbs_get_ctx(ctx : *mut super::ibverbs:: ibv_context) -> *mut super::ibverbs:: verbs_context);
