// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_accept(id : *mut rdma_cm_id, conn_param : *mut rdma_conn_param) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_ack_cm_event(event : *mut rdma_cm_event) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_bind_addr(id : *mut rdma_cm_id, addr : *mut bnd_posix::posix::socket:: sockaddr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_connect(id : *mut rdma_cm_id, conn_param : *mut rdma_conn_param) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_create_ep(id : *mut *mut rdma_cm_id, res : *mut rdma_addrinfo, pd : *mut super::ibverbs:: ibv_pd, qp_init_attr : *mut super::ibverbs:: ibv_qp_init_attr) -> i32);
windows_link::link!("rdmacm" "C" fn rdma_create_event_channel() -> *mut rdma_event_channel);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_create_id(channel : *mut rdma_event_channel, id : *mut *mut rdma_cm_id, context : *mut core::ffi::c_void, ps : rdma_port_space) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_create_qp(id : *mut rdma_cm_id, pd : *mut super::ibverbs:: ibv_pd, qp_init_attr : *mut super::ibverbs:: ibv_qp_init_attr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_create_qp_ex(id : *mut rdma_cm_id, qp_init_attr : *mut super::ibverbs:: ibv_qp_init_attr_ex) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_destroy_ep(id : *mut rdma_cm_id));
windows_link::link!("rdmacm" "C" fn rdma_destroy_event_channel(channel : *mut rdma_event_channel));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_destroy_id(id : *mut rdma_cm_id) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_destroy_qp(id : *mut rdma_cm_id));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_disconnect(id : *mut rdma_cm_id) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_establish(id : *mut rdma_cm_id) -> i32);
windows_link::link!("rdmacm" "C" fn rdma_event_str(event : rdma_cm_event_type) -> *mut i8);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_free_devices(list : *mut *mut super::ibverbs:: ibv_context));
windows_link::link!("rdmacm" "C" fn rdma_freeaddrinfo(res : *mut rdma_addrinfo));
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_cm_event(channel : *mut rdma_event_channel, event : *mut *mut rdma_cm_event) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_devices(num_devices : *mut i32) -> *mut *mut super::ibverbs:: ibv_context);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_dst_port(id : *mut rdma_cm_id) -> bnd_linux::linux::types:: __be16);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_local_addr(id : *mut rdma_cm_id) -> *mut bnd_posix::posix::socket:: sockaddr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_peer_addr(id : *mut rdma_cm_id) -> *mut bnd_posix::posix::socket:: sockaddr);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_remote_ece(id : *mut rdma_cm_id, ece : *mut super::ibverbs:: ibv_ece) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_request(listen : *mut rdma_cm_id, id : *mut *mut rdma_cm_id) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_get_src_port(id : *mut rdma_cm_id) -> bnd_linux::linux::types:: __be16);
windows_link::link!("rdmacm" "C" fn rdma_getaddrinfo(node : *const i8, service : *const i8, hints : *const rdma_addrinfo, res : *mut *mut rdma_addrinfo) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_init_qp_attr(id : *mut rdma_cm_id, qp_attr : *mut super::ibverbs:: ibv_qp_attr, qp_attr_mask : *mut i32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_join_multicast(id : *mut rdma_cm_id, addr : *mut bnd_posix::posix::socket:: sockaddr, context : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_join_multicast_ex(id : *mut rdma_cm_id, mc_join_attr : *mut rdma_cm_join_mc_attr_ex, context : *mut core::ffi::c_void) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_leave_multicast(id : *mut rdma_cm_id, addr : *mut bnd_posix::posix::socket:: sockaddr) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_listen(id : *mut rdma_cm_id, backlog : i32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_migrate_id(id : *mut rdma_cm_id, channel : *mut rdma_event_channel) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_notify(id : *mut rdma_cm_id, event : super::ibverbs:: ibv_event_type) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_reject(id : *mut rdma_cm_id, private_data : *const core::ffi::c_void, private_data_len : u8) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_reject_ece(id : *mut rdma_cm_id, private_data : *const core::ffi::c_void, private_data_len : u8) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_resolve_addr(id : *mut rdma_cm_id, src_addr : *mut bnd_posix::posix::socket:: sockaddr, dst_addr : *mut bnd_posix::posix::socket:: sockaddr, timeout_ms : i32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_resolve_route(id : *mut rdma_cm_id, timeout_ms : i32) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_set_local_ece(id : *mut rdma_cm_id, ece : *mut super::ibverbs:: ibv_ece) -> i32);
#[cfg(feature = "ibverbs")]
windows_link::link!("rdmacm" "C" fn rdma_set_option(id : *mut rdma_cm_id, level : i32, optname : i32, optval : *mut core::ffi::c_void, optlen : u64) -> i32);
pub const IBV_PATH_RECORD_REVERSIBLE: i32 = 128i32;
pub const RAI_FAMILY: i32 = 8i32;
pub const RAI_NOROUTE: i32 = 4i32;
pub const RAI_NUMERICHOST: i32 = 2i32;
pub const RAI_PASSIVE: i32 = 1i32;
pub const RDMA_CM_EVENT_ADDR_CHANGE: u32 = 14u32;
pub const RDMA_CM_EVENT_ADDR_ERROR: u32 = 1u32;
pub const RDMA_CM_EVENT_ADDR_RESOLVED: u32 = 0u32;
pub const RDMA_CM_EVENT_CONNECT_ERROR: u32 = 6u32;
pub const RDMA_CM_EVENT_CONNECT_REQUEST: u32 = 4u32;
pub const RDMA_CM_EVENT_CONNECT_RESPONSE: u32 = 5u32;
pub const RDMA_CM_EVENT_DEVICE_REMOVAL: u32 = 11u32;
pub const RDMA_CM_EVENT_DISCONNECTED: u32 = 10u32;
pub const RDMA_CM_EVENT_ESTABLISHED: u32 = 9u32;
pub const RDMA_CM_EVENT_MULTICAST_ERROR: u32 = 13u32;
pub const RDMA_CM_EVENT_MULTICAST_JOIN: u32 = 12u32;
pub const RDMA_CM_EVENT_REJECTED: u32 = 8u32;
pub const RDMA_CM_EVENT_ROUTE_ERROR: u32 = 3u32;
pub const RDMA_CM_EVENT_ROUTE_RESOLVED: u32 = 2u32;
pub const RDMA_CM_EVENT_TIMEWAIT_EXIT: u32 = 15u32;
pub const RDMA_CM_EVENT_UNREACHABLE: u32 = 7u32;
pub const RDMA_CM_JOIN_MC_ATTR_ADDRESS: u32 = 1u32;
pub const RDMA_CM_JOIN_MC_ATTR_JOIN_FLAGS: u32 = 2u32;
pub const RDMA_CM_JOIN_MC_ATTR_RESERVED: u32 = 4u32;
pub const RDMA_IB_IP_PORT_MASK: i32 = 65535i32;
pub const RDMA_IB_IP_PS_MASK: u64 = 18446744073709486080u64;
pub const RDMA_IB_IP_PS_TCP: i32 = 17170432i32;
pub const RDMA_IB_IP_PS_UDP: i32 = 17891328i32;
pub const RDMA_IB_PS_IB: i32 = 20905984i32;
pub const RDMA_MAX_INIT_DEPTH: u32 = 255u32;
pub const RDMA_MAX_RESP_RES: u32 = 255u32;
pub const RDMA_MC_JOIN_FLAG_FULLMEMBER: u32 = 0u32;
pub const RDMA_MC_JOIN_FLAG_RESERVED: u32 = 2u32;
pub const RDMA_MC_JOIN_FLAG_SENDONLY_FULLMEMBER: u32 = 1u32;
pub const RDMA_OPTION_IB: u32 = 1u32;
pub const RDMA_OPTION_IB_PATH: u32 = 1u32;
pub const RDMA_OPTION_ID: u32 = 0u32;
pub const RDMA_OPTION_ID_ACK_TIMEOUT: u32 = 3u32;
pub const RDMA_OPTION_ID_AFONLY: u32 = 2u32;
pub const RDMA_OPTION_ID_REUSEADDR: u32 = 1u32;
pub const RDMA_OPTION_ID_TOS: u32 = 0u32;
pub const RDMA_PS_IB: u32 = 319u32;
pub const RDMA_PS_IPOIB: u32 = 2u32;
pub const RDMA_PS_TCP: u32 = 262u32;
pub const RDMA_PS_UDP: u32 = 273u32;
pub const RDMA_UDP_QKEY: i32 = 19088743i32;
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct ibv_path_data {
    pub flags: u32,
    pub reserved: u32,
    pub path: ibv_path_record,
}
#[cfg(feature = "ibverbs")]
impl Default for ibv_path_data {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct ibv_path_record {
    pub service_id: bnd_linux::linux::types::__be64,
    pub dgid: super::ibverbs::ibv_gid,
    pub sgid: super::ibverbs::ibv_gid,
    pub dlid: bnd_linux::linux::types::__be16,
    pub slid: bnd_linux::linux::types::__be16,
    pub flowlabel_hoplimit: bnd_linux::linux::types::__be32,
    pub tclass: u8,
    pub reversible_numpath: u8,
    pub pkey: bnd_linux::linux::types::__be16,
    pub qosclass_sl: bnd_linux::linux::types::__be16,
    pub mtu: u8,
    pub rate: u8,
    pub packetlifetime: u8,
    pub preference: u8,
    pub reserved: [u8; 6],
}
#[cfg(feature = "ibverbs")]
impl Default for ibv_path_record {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct ibv_sa_mcmember_rec {
    pub mgid: super::ibverbs::ibv_gid,
    pub port_gid: super::ibverbs::ibv_gid,
    pub qkey: u32,
    pub mlid: u16,
    pub mtu_selector: u8,
    pub mtu: u8,
    pub traffic_class: u8,
    pub pkey: u16,
    pub rate_selector: u8,
    pub rate: u8,
    pub packet_life_time_selector: u8,
    pub packet_life_time: u8,
    pub sl: u8,
    pub flow_label: u32,
    pub hop_limit: u8,
    pub scope: u8,
    pub join_state: u8,
    pub proxy_join: i32,
}
#[cfg(feature = "ibverbs")]
impl Default for ibv_sa_mcmember_rec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct ibv_sa_path_rec {
    pub dgid: super::ibverbs::ibv_gid,
    pub sgid: super::ibverbs::ibv_gid,
    pub dlid: bnd_linux::linux::types::__be16,
    pub slid: bnd_linux::linux::types::__be16,
    pub raw_traffic: i32,
    pub flow_label: bnd_linux::linux::types::__be32,
    pub hop_limit: u8,
    pub traffic_class: u8,
    pub reversible: i32,
    pub numb_path: u8,
    pub pkey: bnd_linux::linux::types::__be16,
    pub sl: u8,
    pub mtu_selector: u8,
    pub mtu: u8,
    pub rate_selector: u8,
    pub rate: u8,
    pub packet_life_time_selector: u8,
    pub packet_life_time: u8,
    pub preference: u8,
}
#[cfg(feature = "ibverbs")]
impl Default for ibv_sa_path_rec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct ibv_sa_service_rec {
    pub id: u64,
    pub gid: super::ibverbs::ibv_gid,
    pub pkey: u16,
    pub lease: u32,
    pub key: [u8; 16],
    pub name: [u8; 64],
    pub data8: [u8; 16],
    pub data16: [u16; 8],
    pub data32: [u32; 4],
    pub data64: [u64; 2],
}
#[cfg(feature = "ibverbs")]
impl Default for ibv_sa_service_rec {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_addr {
    pub rdma_addr__anon_0: rdma_addr__anon_0,
    pub rdma_addr__anon_1: rdma_addr__anon_1,
    pub addr: rdma_addr_addr,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_addr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union rdma_addr__anon_0 {
    pub src_addr: bnd_posix::posix::socket::sockaddr,
    pub src_sin: bnd_posix::posix::inet::sockaddr_in,
    pub src_sin6: bnd_posix::posix::inet::sockaddr_in6,
    pub src_storage: bnd_posix::posix::socket::sockaddr_storage,
}
impl Default for rdma_addr__anon_0 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub union rdma_addr__anon_1 {
    pub dst_addr: bnd_posix::posix::socket::sockaddr,
    pub dst_sin: bnd_posix::posix::inet::sockaddr_in,
    pub dst_sin6: bnd_posix::posix::inet::sockaddr_in6,
    pub dst_storage: bnd_posix::posix::socket::sockaddr_storage,
}
impl Default for rdma_addr__anon_1 {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub union rdma_addr_addr {
    pub ibaddr: rdma_ib_addr,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_addr_addr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rdma_addrinfo {
    pub ai_flags: i32,
    pub ai_family: i32,
    pub ai_qp_type: i32,
    pub ai_port_space: i32,
    pub ai_src_len: bnd_posix::posix::unistd::socklen_t,
    pub ai_dst_len: bnd_posix::posix::unistd::socklen_t,
    pub ai_src_addr: *mut bnd_posix::posix::socket::sockaddr,
    pub ai_dst_addr: *mut bnd_posix::posix::socket::sockaddr,
    pub ai_src_canonname: *mut i8,
    pub ai_dst_canonname: *mut i8,
    pub ai_route_len: u64,
    pub ai_route: *mut core::ffi::c_void,
    pub ai_connect_len: u64,
    pub ai_connect: *mut core::ffi::c_void,
    pub ai_next: *mut rdma_addrinfo,
}
impl Default for rdma_addrinfo {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_cm_event {
    pub id: *mut rdma_cm_id,
    pub listen_id: *mut rdma_cm_id,
    pub event: rdma_cm_event_type,
    pub status: i32,
    pub param: rdma_cm_event_param,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_cm_event {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub union rdma_cm_event_param {
    pub conn: rdma_conn_param,
    pub ud: rdma_ud_param,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_cm_event_param {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rdma_cm_event_type = u32;
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_cm_id {
    pub verbs: *mut super::ibverbs::ibv_context,
    pub channel: *mut rdma_event_channel,
    pub context: *mut core::ffi::c_void,
    pub qp: *mut super::ibverbs::ibv_qp,
    pub route: rdma_route,
    pub ps: rdma_port_space,
    pub port_num: u8,
    pub event: *mut rdma_cm_event,
    pub send_cq_channel: *mut super::ibverbs::ibv_comp_channel,
    pub send_cq: *mut super::ibverbs::ibv_cq,
    pub recv_cq_channel: *mut super::ibverbs::ibv_comp_channel,
    pub recv_cq: *mut super::ibverbs::ibv_cq,
    pub srq: *mut super::ibverbs::ibv_srq,
    pub pd: *mut super::ibverbs::ibv_pd,
    pub qp_type: super::ibverbs::ibv_qp_type,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_cm_id {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rdma_cm_join_mc_attr_ex {
    pub comp_mask: u32,
    pub join_flags: u32,
    pub addr: *mut bnd_posix::posix::socket::sockaddr,
}
impl Default for rdma_cm_join_mc_attr_ex {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rdma_cm_join_mc_attr_mask = u32;
pub type rdma_cm_mc_join_flags = u32;
#[repr(C, packed(8))]
#[derive(Clone, Copy)]
pub struct rdma_conn_param {
    pub private_data: *mut core::ffi::c_void,
    pub private_data_len: u8,
    pub responder_resources: u8,
    pub initiator_depth: u8,
    pub flow_control: u8,
    pub retry_count: u8,
    pub rnr_retry_count: u8,
    pub srq: u8,
    pub qp_num: u32,
}
impl Default for rdma_conn_param {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(4))]
#[derive(Clone, Copy, Default)]
pub struct rdma_event_channel {
    pub fd: i32,
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_ib_addr {
    pub sgid: super::ibverbs::ibv_gid,
    pub dgid: super::ibverbs::ibv_gid,
    pub pkey: bnd_linux::linux::types::__be16,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_ib_addr {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type rdma_port_space = u32;
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_route {
    pub addr: rdma_addr,
    pub path_rec: *mut ibv_sa_path_rec,
    pub num_paths: i32,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_route {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C, packed(8))]
#[cfg(feature = "ibverbs")]
#[derive(Clone, Copy)]
pub struct rdma_ud_param {
    pub private_data: *mut core::ffi::c_void,
    pub private_data_len: u8,
    pub ah_attr: super::ibverbs::ibv_ah_attr,
    pub qp_num: u32,
    pub qkey: u32,
}
#[cfg(feature = "ibverbs")]
impl Default for rdma_ud_param {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
