// Bindings generated by `windows-bindgen` 0.66.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

#[cfg(feature = "ibverbs")]
pub mod ibverbs;
#[cfg(feature = "rdmacm")]
pub mod rdmacm;
#[cfg(feature = "wrapper")]
pub mod wrapper;
